---
groups:
- name: queue-master-jobs
  jobs:
  - build-queue-master
  - deploy-queue-master-to-stage
  - health-check
  - deploy-queue-master-to-prod
  - execute-queue-master-load-tests
  - validate-queue-master-load-test
  - promote-new-version-queue-master

- name: init-dynatrace
  jobs: 
  - init-dynatrace-queue-master

resource_types:
- name: dynatrace-resource
  type: docker-image
  source:
    repository: mvilliger/dynatrace-resource

resources:

- name: git-pipeline
  type: git
  source:
    branch: master
    uri: https://github.com/((workshop-repository))/sockshop.git

- name: git-jmeter-as-container
  type: git
  source:
    branch: master
    uri: https://github.com/((workshop-repository))/jmeter-as-container.git

- name: git-queue-master
  type: git
  source:
    branch: master
    uri: https://github.com/((workshop-repository))/queue-master.git

- name: dynatrace
  type: dynatrace-resource
  source:
    apitoken: ((apitoken))
    tenanthost: ((tenanthost))

- name: queue-master-release-bucket
  type: s3
  source:
    region_name: eu-west-1
    regexp: queue-master/queue-master-(.*).jar
    bucket: ((s3-bucket))
    access_key_id: ((s3-access-key-id))
    secret_access_key: ((s3-secret-access-key))

- name: version
  type: semver
  source:
#    driver: s3
#    initial_version: 0.0.1
#    region_name: eu-west-1
#    bucket: ((s3-bucket))
#    access_key_id: ((s3-access-key-id))
#    secret_access_key: ((s3-secret-access-key))
#    key: queue-master/version
    driver: git
    uri: https://github.com/((workshop-repository))/queue-master.git
    branch: master
    file: version

# PCF Environments

- name: pcf-stage
  type: cf
  source:
    api: ((pcf-stage-api))
    username: ((pcf-stage-deploy-username))
    password: ((pcf-stage-deploy-password))
    organization: ((pcf-stage-organization))
    space: ((pcf-stage-space))
    skip_cert_check: false

- name: pcf-production
  type: cf
  source:
    api: ((pcf-prod-api))
    username: ((pcf-prod-deploy-username))
    password: ((pcf-prod-deploy-password))
    organization: ((pcf-prod-organization))
    space: ((pcf-prod-space))
    skip_cert_check: false

jobs:

# Initialize Dynatrace Custom Device

- name: init-dynatrace-queue-master
  public: true
  plan:
  - aggregate:
    - get: git-pipeline
    - get: git-queue-master
  - task: init-dynatrace-task
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/init-dynatrace-task.yml
    params: 
      apitoken: ((apitoken))
      tenanthost: ((tenanthost))
      APP_REPO: git-queue-master

# QUEUE-MASTER

- name: build-queue-master
  plan:
  - get: git-queue-master
    trigger: true
  - get: version
    params: { pre: rc }
  - task: mvn-build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: maven, tag: 3.2-jdk-8}
      inputs:
      - name: git-queue-master
      - name: version
      outputs:
      - name: workspace
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          # Caching Maven
          export ROOT_FOLDER=$( pwd )
          M2_HOME="${HOME}/.m2"
          M2_CACHE="${ROOT_FOLDER}/maven"
          echo "Generating symbolic link for Maven cache"
          ln -s "${M2_CACHE}" "${M2_HOME}"

          # Build App
          output_dir=workspace
          cd git-queue-master
          mvn -DskipTests package
          cd ..
          mv git-queue-master/target/queue-master.jar git-queue-master/target/queue-master-$(cat version/number).jar
          cp git-queue-master/target/queue-master-*.jar "${output_dir}/"
      caches:
        - path: maven
  - put: queue-master-release-bucket
    params:
      file: workspace/queue-master-*.jar

- name: deploy-queue-master-to-stage
  serial: true
  public: true
  plan:
  - get: git-queue-master
    trigger: true
    passed:
      - build-queue-master
  - get: queue-master-release-bucket
    passed:
      - build-queue-master
  - get: git-pipeline
    trigger: false      
  - task: prepare-app-manifest
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/app-manifest-prep.yml
    params:
      PCF_APP_SUFFIX: ((pcf-stage-queue-master-suffix)) 
      APP_REPO: git-queue-master
  - put: dynatrace
    params:
      monspecserviceenvironment: queue-master/Staging
      pipelinetaskname: deploy-queue-master-to-stage
      deployversion: v1.0
      APP_REPO: git-queue-master 
  - put: pcf-stage
    params:
      path: queue-master-release-bucket/queue-master-*.jar
      manifest: app-manifest-output/manifest.yml 
  
- name: health-check
  serial: true
  public: true
  plan:
  - aggregate:
    - get: git-queue-master
      trigger: true
      passed:
        - deploy-queue-master-to-stage
    - get: git-jmeter-as-container
    - get: git-pipeline
  - task: run-load-tests
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/health-test.yml
    params:
      APP_REPO: git-jmeter-as-container
      FUNC_VALIDATION: yes
      PRODUCTION: false
      SCRIPT_NAME: basiccheck.jmx
      PCF_APP_SUFFIX: ((pcf-stage-queue-master-suffix))
      PCF_APP_DOMAIN: ((pcf-prod-app-domain))
      DT_LTN: HealthCheck
      VUCount: 1
      LoopCount: 1

- name: deploy-queue-master-to-prod
  serial: true
  public: true
  plan:
  - get: git-queue-master
    trigger: true
    passed:
      - health-check
  - get: queue-master-release-bucket
    passed:
      - build-queue-master 
  - get: git-pipeline
    trigger: false
  - task: get-current-app-color
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/current-app-get-info.yml
    params:
      PCF_APP_SUFFIX: ((pcf-prod-queue-master-suffix))
      PCF_API: ((pcf-prod-api))
      PCF_ORG: ((pcf-prod-organization))
      PCF_USER: ((pcf-prod-deploy-username))
      PCF_PWD: ((pcf-prod-deploy-password))
      PCF_SPACE: ((pcf-prod-space))              
  - task: prepare-app-manifest
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/app-manifest-prep.yml
    params:
      PCF_APP_SUFFIX: ((pcf-prod-queue-master-suffix)) 
      APP_REPO: git-queue-master
      PRODUCTION: true       
  - put: dynatrace
    params:
      monspecserviceenvironment: queue-master/Production
      pipelinetaskname: deploy-queue-master-to-prod
      deployversion: v1.0 
      APP_REPO: git-queue-master      
  - put: pcf-production
    params:
      path: queue-master-release-bucket/queue-master-*.jar
      manifest: app-manifest-output/manifest.yml 

- name: execute-queue-master-load-tests
  serial: true
  public: true
  plan:
  - aggregate:
    - get: git-queue-master
      trigger: true
      passed:
        - deploy-queue-master-to-prod
    - get: git-jmeter-as-container
    - get: git-pipeline
      trigger: false        
  - task: get-current-app-color
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/current-app-get-info.yml
    params:
      PCF_APP_SUFFIX: ((pcf-prod-queue-master-suffix))
      PCF_API: ((pcf-prod-api))
      PCF_ORG: ((pcf-prod-organization))
      PCF_USER: ((pcf-prod-deploy-username))
      PCF_PWD: ((pcf-prod-deploy-password))
      PCF_SPACE: ((pcf-prod-space))           
  - task: run-load-test
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/load-tests.yml
    params:
      APP_REPO: git-jmeter-as-container
      FUNC_VALIDATION: yes
      PRODUCTION: true
      SCRIPT_NAME: queue-master.jmx
      PCF_APP_SUFFIX: ((pcf-prod-queue-master-suffix))
      PCF_APP_DOMAIN: ((pcf-prod-app-domain))
      DT_LTN: LoadTest
      VUCount: 5
      LoopCount: 20    
  - task: push-dynatrace-monspec-data
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/push-dynatrace-monspec-data.yml
    params: 
      monspecserviceenvironment: queue-master/Production-$NEXT_APP_COLOR
      apitoken: ((apitoken))
      tenanthost: ((tenanthost))
      APP_REPO: git-queue-master   

- name: validate-queue-master-load-test
  serial: true
  public: true
  plan:
  - get: git-queue-master
    trigger: true
    passed:
      - execute-queue-master-load-tests
  - get: git-pipeline
    trigger: false      
  - task: get-current-app-color
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/current-app-get-info.yml
    params:
      PCF_APP_SUFFIX: ((pcf-prod-queue-master-suffix))
      PCF_API: ((pcf-prod-api))
      PCF_ORG: ((pcf-prod-organization))
      PCF_USER: ((pcf-prod-deploy-username))
      PCF_PWD: ((pcf-prod-deploy-password))
      PCF_SPACE: ((pcf-prod-space))       
  - task: validate-via-monspec
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/validate-via-monspec.yml
    params: 
      monspeccomparison: queue-master/Production-$NEXT_APP_COLOR\ToProduction-$CURRENT_APP_COLOR\Last5m
      apitoken: ((apitoken))
      tenanthost: ((tenanthost))
      APP_REPO: git-queue-master     

- name: promote-new-version-queue-master
  serial: true
  public: true
  plan:
  - get: git-queue-master
    trigger: true
    passed:
      - validate-queue-master-load-test
  - get: version
    params: { bump: patch }
  - get: git-pipeline
    trigger: false      
  - task: get-current-app-color
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/current-app-get-info.yml
    params:
      PCF_APP_SUFFIX: ((pcf-prod-queue-master-suffix))
      PCF_API: ((pcf-prod-api))
      PCF_ORG: ((pcf-prod-organization))
      PCF_USER: ((pcf-prod-deploy-username))
      PCF_PWD: ((pcf-prod-deploy-password))
      PCF_SPACE: ((pcf-prod-space))   
  - task: switch-app-routes
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/update-routes.yml
    params:
      PCF_APP_SUFFIX: ((pcf-prod-queue-master-suffix))
      PCF_API: ((pcf-prod-api))
      PCF_ORG: ((pcf-prod-organization))
      PCF_USER: ((pcf-prod-deploy-username))
      PCF_PWD: ((pcf-prod-deploy-password))
      PCF_SPACE: ((pcf-prod-space))
      PCF_APP_DOMAIN: ((pcf-prod-app-domain))              
#  - put: version
#    params: { file: version/number }